### ISSUE TITLE
Unable to get to craft Pontus World Gate.

### ISSUE THREAD

**Issue by xenxero1** [kenijey/harshencastle#115]
There is a lack of in-game documentaton on how to enter the Pontus dimension. My players have found plenty of gate spawner parts and Harshen ingots, but can't figure out any way to put the parts together, or open the portal. 

Could you please add some kind of in-game documentation that will handle this kind of information, or at least give a brief explanation here for the sake of documenting it somewhere?

**Comment by Wyn-Price** [comment]
In game documentation is something I do plan to add, however I haven't been able to work on this for a while (and won't be for a couple of weeks) due to exams. 
 
All recipes **should** be in JEI, but if that's failed it could mean a API upgrade. I think I have time tonight, so I'll look into fixing JEI.

I can't fully remember the recipe, but I can get a screenshot of what to do in a couple of hours, when school ends

**Comment by xenxero1** [comment]
Ah thank you. I have no idea why it wasn't showing up in my JEI, but I can check again later tonight. It could be that the ritual itself was in JEI but it didn't link from the Pontus gate spawner or it's pieces.

**Comment by Wyn-Price** [comment]
What are your versions of everything?

**Comment by xenxero1** [comment]
I am using the 1.3.4 version of this pack, for Minecraft 1.12.2.
https://www.curseforge.com/minecraft/modpacks/minecraft-mage

I don't have the mod-list on hand, but I know a majority of the mods are up-to-date as of it's release.

**Comment by xenxero1** [comment]
I can confirm that lightning rituals are not displayed in JEI in my current version of the mods. Regarding crafting, is it just a matter of putting everything on to the pedestals, or do I need some kind of activator?

**Comment by Wyn-Price** [comment]
Putting everything in the pedestals WITH the gold blocks underneath

**Comment by kenijey** [comment]
This issue doesn’t appear at my side. I even tried in my modpack, ritual recipies are there.
