### ISSUE TITLE
JEI Recipe TODOs

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#8]
**Ladle:**
Need to show Ladle in Cauldron Recipe Page

**Harshen Soul Fragment:**
-Need to show it obtainable from Harshen Soul Ore and the Soul Harsher Pickaxe needed

**Harshen Crystal:**
-Need to show it is obtainable from Harshen Soul Flower

**Light Emitted Essence and Light Emitted Seed:**
-Same procedure

**Itium:**
-From Itium Ore  (same procedure)

**Soul Harsher Pickaxe:**
-Need to show a GUI that tells you can obtain it from Kazzendre's Castle

AND MOB DROPS
-Blood Essence: Obtainable from Bloody Marry (when it's ready)

**Comment by kenijey** [comment]
Need to add Blood Ritual also.
3x3 soul sands, ritual pedestal slab and bloods

**Comment by Wyn-Price** [comment]
itium from itium ore is quite easy to understand, and the soul fragment could have a JEI description instead of its own JEI page. the pickaxe can also have the description. with the crops, there are some mods that do that for you, and its pretty easy to spot that the plant does that; ill add a description for the harshen crystal
